AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Automatic database shut down and start up Lambda functions
Parameters:
  ClusterID: # RDS Cluster ID
    Type: String
Globals:
  Function:
    MemorySize: 128
    Timeout: 3
    Handler: app.lambdaHandler
    Runtime: nodejs16.x
    Environment:
      Variables:
        DB_CLUSTER: !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${ClusterID}
Resources:
  DBShutDownFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: shut-down/
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds:StopDBCluster
              Resource: !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${ClusterID}
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 ? * MON-FRI *)
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref DBFunctionsDeadLetterTopic
  DBStartUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: start-up/
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds:StartDBCluster
              Resource: !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${ClusterID}
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 7 ? * MON-FRI *)
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref DBFunctionsDeadLetterTopic
  DBFunctionsDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: lmiranda@brooklynva.com
          Protocol: email
